services:
  nnoel:
    image: ghcr.io/desdpy/nnoel-neural-network-on-a-leash:latest
    ports:
      - "${NNOEL_PORT:-5000}:5000"
    environment:
      # Needed so last log doesn't get stuck in buffer
      PYTHONUNBUFFERED: "1"
    volumes:
      - models_data:/app/models
    restart: unless-stopped

volumes:
  models_data:
