services:
  nnoel:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Needed so last log doesn't get stuck in buffer
      PYTHONUNBUFFERED: "1"
    volumes:
      - models_data:/app/models
    restart: unless-stopped

volumes:
  models_data:
